### ISSUE TITLE
Broader reach on AWS resources

### ISSUE THREAD

**Issue by kennethgds** [warrensbox/aws-find#32] opened 2019-07-02 16:04 UTC
It would be great if you can probably expand this tool to other AWS resources as well. 

Something like finding the **_Database Name_** from bunch of mysql resources or **_Cloudfront Distro_** name with the help of Tags. 

Probably like an addition of another variable which switches between resources. It'll be useful for faster reference.

**Comment by rakeshmaddineni** [comment] 2019-07-02 17:20
I would like to take a look at it and contribute.

**Comment by warrensbox** [comment] 2019-07-02 17:35
I will assign this Rakesh. I will merge it once the function is working as intended. 
@kennethgds @rakeshmaddineni

**Comment by kennethgds** [comment] 2019-07-02 18:39
You can find a similar setup here: https://github.com/wallix/awless

**Closed** 2022-06-19 17:38 UTC
Labels: enhancement
